version: '3.7'

services:

  es:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
      container_name: es
      environment:
            - node.name=es
            - discovery.type=single-node
            - cluster.name=es-docker-cluster
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
            memlock:
                soft: -1
                hard: -1
      volumes:
            - ./es:/var/lib/elasticsearch/data
      ports:
            - 9200:9200

  kibana:
        image: docker.elastic.co/kibana/kibana:7.11.2
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://es:9200
            ELASTICSEARCH_HOSTS: '["http://es:9200"]'

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
        - 8081:8081
    environment:
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_SERVER=mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
        - 27017:27017
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin

  node-ms-service:
    build: .
    image:  node-ms-service
    ports:
        - 3001:3001
    container_name: node-ms-service
    depends_on:
        - mongo
    environment:
        PORT: 3001
        MONGO_USER: admin
        MONGO_PASS: admin
        MONGO_HOST: mongo
        MONGO_PORT: 27017
        MONGO_DB_NAME: teste
